dist: wheezy
sudo: required
dist: trusty
addons:
  apt:
    packages:
      - python-dev

language: go

git:
  depth: 10

branches:
  only:
    - master

env:
  global:
    - SOURCE_DIR="quickstart"
    - DESTINATION_PATH="https://devicesimulatorstorage.blob.core.windows.net/mytestsite"
    - CDN_RESOURCE_GROUP="saroup"
    - CDN_ENDPOINT_NAME="devicesimulatorcdnendpoint"
    - CDN_PROFILE="contentdeliverynetwork"

install: 
  - go get -u -v github.com/spf13/hugo
  - echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ wheezy main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys 417A0893
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list' 
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 417A0893
  - curl https://packages.microsoft.com/config/ubuntu/14.04/prod.list > ./microsoft-prod.list
  - sudo cp ./microsoft-prod.list /etc/apt/sources.list.d/
  - curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
  - sudo cp ./microsoft.gpg /etc/apt/trusted.gpg.d/
  - sudo echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-trusty-prod/ trusty main" > azure.list
  - sudo cp ./azure.list /etc/apt/sources.list.d/
  - sudo apt-key adv --keyserver packages.microsoft.com --recv-keys B02C46DF417A0893
  - sudo apt-get update
  - sudo apt-get install azcopy=6.0.0
  - sudo apt-get install apt-transport-https azure-cli

# Build the website
script:
  - dpkg -s azcopy
  - mkdir themes
  - git clone https://github.com/budparr/gohugo-theme-ananke.git themes/ananke
  - hugo
  - azcopy --source $SOURCE_DIR --destination $DESTINATION_PATH --dest-key $AZURE_STORAGE_ACCESS_KEY --recursive --quiet --set-content-type
  - az login --service-principal -u $AZURE_SERVICE_PRINCIPAL_APP_ID --password $AZURE_SERVICE_PRINCIPAL_APP_PASSWORD --tenant $AZURE_SERVICE_PRINCIPAL_TENANT
  - az cdn endpoint purge -g $CDN_RESOURCE_GROUP -n $CDN_ENDPOINT_NAME --profile-name $CDN_PROFILE --content-paths "/*"
   
